version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.7
jobs:
  build:
    docker:
      - image: cimg/node:lts-browsers
    environment:
      # TODO: remove after proper node 18 migration
      NODE_OPTIONS: --openssl-legacy-provider

    working_directory: ~/repo

    steps:
      - checkout

      - browser-tools/install-browser-tools

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # catch build-time errors (if any)
      - run: yarn build:lib

      - store_artifacts:
          path: ./dist/lib/VueProductCarousel.umd.min.js
          destination: VueProductCarousel.umd.min.js

      - store_artifacts:
          path: ./dist/lib/VueProductCarousel.css
          destination: VueProductCarousel.css

      - run:
          name: Run code-style check
          command: yarn lint --format junit -o /tmp/test-results/code-style-test-results.xml

      - run:
          name: Run E2E tests
          command: yarn test:e2e:ci

      - store_test_results:
          path: /tmp/test-results
